name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          .cpcache
          ~/.m2/repository
        key: ${{ runner.os }}-deps-${{ hashFiles('**/deps.edn') }}

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@3.0
      with:
        tools-deps: '1.10.1.469'

    - name: Build
      run: clojure -T:build test
