name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          .cpcache
          ~/.m2/repository
        key: ${{ runner.os }}-deps-${{ hashFiles('**/deps.edn') }}

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@3.0
      with:
        tools-deps: '1.10.1.469'

    - name: Build
      run: clojure -T:build test

    - name: Docs
      run: clojure -X:codox

    - name: Deploy Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: target/doc
