name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Cache
      uses: actions/cache@v4.2.3
      with:
        path: |
          .cpcache
          ~/.m2/repository
        key: ${{ runner.os }}-deps-${{ hashFiles('**/deps.edn') }}

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@13.4
      with:
        tools-deps: '1.12.1.1550'

    - name: Test
      run: clojure -T:build test
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
