name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          .cpcache
          ~/.m2/repository
        key: ${{ runner.os }}-deps-${{ hashFiles('**/deps.edn') }}

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@3.0
      with:
        tools-deps: '1.11.1.1208'

    - name: Build
      run: clojure -T:build test
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    - name: Docs
      run: clojure -X:codox

    - name: Deploy Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        FOLDER: target/doc
